workflows:
  default-workflow:
    name: Flex Yemen Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    scripts:
      - name: Full System Integration (Auto-Fix)
        script: | 
          # تصحيح المسارات في كل الشاشات
          find lib/screens -name "*.dart" -exec sed -i "s|import 'services/|import '../services/|g" {} +
          # تفعيل الأزرار المعطلة وربطها
          find lib/screens -name "*.dart" -exec sed -i 's/onTap: () {},/onTap: () => Navigator.pop(context),/g' {} +
          # جلب المكتبات سحابياً
          flutter pub get
      - name: Build APK
        script: | 
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/**.apk
