workflows:
  android-workflow:
    name: Yemen Market Final Build
    max_build_duration: 60
    environment:
      flutter: stable
      java: 17
    scripts:
      - name: Reconstruct and Clean
        script: |
          rm -rf android build
          flutter create . --platforms android --org com.yemen.market
          flutter pub get
      - name: Build Android APK
        script: |
          flutter build apk --release --no-tree-shake-icons
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
