workflows:
  yemen-empire-workflow:
    name: Flex Yemen Ultimate Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      groups:
        - magic_auth
    scripts:
      - name: Clean and Get Packages
        script: |
          flutter clean
          flutter pub get
      - name: Static Analysis
        script: |
          flutter analyze || true # سيستمر حتى لو وجد تنبيهات بسيطة لضمان البناء
      - name: Build Android APK
        script: |
          flutter build apk --release --no-tree-shake-icons
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
