workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 60
    instance_type: mac_mini_m1
    scripts:
      - name: Get Flutter packages
        script: flutter packages pub get
      - name: Build Android APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/**/app-release.apk
    publishing:
      email:
        recipients:
          - your_email@example.com # ضع إيميلك هنا لتصلك النسخة
