workflows:
  main-workflow:
    name: Yemen Project Build
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Get dependencies
        script: flutter pub get
      - name: Generate Launcher Icons
        script: flutter pub run flutter_launcher_icons
      - name: Build APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
