name: yemen_project
description: Flex Yemen Market App
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  local_auth: ^2.1.6
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  path: ^1.8.3
  # إضافة الحزمة المفقودة التي تسببت في الخطأ
  mobile_scanner: ^5.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/logo.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/logo.png
