name: yemen_project
description: Flex Yemen Super App
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  supabase_flutter: ^2.0.2
  google_maps_flutter: ^2.5.3
  local_auth: ^2.1.6
  share_plus: ^7.2.1
  flutter_local_notifications: ^17.0.0
  image_picker: ^1.0.7
  path: ^1.8.3
  pdf: ^3.10.8
  printing: ^5.11.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

# تعديل الإعدادات لتجنب البحث عن ملفات آيفون مفقودة
flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
