workflows:
  flex-yemen-release:
    name: Flex Yemen Auto-Rebuild
    max_build_duration: 30
    instance_type: mac_mini_m1
    environment:
      flutter: stable
    scripts:
      - name: 1. Auto Reconstruct Android
        script: |
          # حذف المجلد القديم لضمان عدم وجود تعارضات
          rm -rf android
          # إعادة إنشاء المجلد باستخدام الأمر الذي طلبته
          flutter create . --platforms android --org com.almwld
          # ربط الـ SDK لضمان عمل المكتبات الخارجية
          echo "flutter.sdk=$FLUTTER_ROOT" > android/local.properties
      - name: 2. Build Android APK
        script: |
          flutter pub get
          flutter build apk --release --obfuscate --split-debug-info=symbols
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
    publishing:
      email:
        recipients:
          - Binobaeid@gmail.com
